apiVersion: apps/v1
kind: Deployment
metadata:
  name: notpad-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notpad-app
  template:
    metadata:
      labels:
        app: notpad-app
    spec:
      containers:
      - name: k8s-demo
        image: kareembaher/notepad`
        ports:
        - name: notepad-port
          containerPort: 8080
        env:
          - name: ENV_TEST_MYSQL_HOST
            value: database-service
          - name: SPRING_PROFILES_ACTIVE
            value: test
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: notepad-secrets
                key: database
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notepad-secrets
                key: password
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: cred-volume
        secret: 
          secretName: db-secrets